name: CI

on:
  pull_request:
  push:

jobs:
  mix_test:
    name: mix test

    # prevent workflow jobs run twice on push and pull_request event
    # see https://github.com/orgs/community/discussions/57827
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.20.2
          otp-version: 28.5.0.2

      - name: Restore deps and _build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile
        env:
          MIX_ENV: test

      - name: Run tests
        run: |
          epmd -daemon
          mix test
